version: 0.2

phases:
  install:
    commands:
      - npm install
  pre_build:
    commands:
      - npm run build
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
