version: 0.2

phases:
  install:
    commands:
      - npm install -g npm@9
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - npm run migrate
artifacts:
  files:
    - '**/*'
