version: 0.2

phases:
  build:
    commands:
      - npm install -g npm@9
      - npm install
      - npm run build

artifacts:
  files:
    - .platform/**/*
    - dist/**/*
    - prisma/**/*
    - package-lock.json
    - package.json

cache:
  paths:
    - node_modules/**/*
